# Generated by Django 5.0.4 on 2025-03-26 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storyBridge', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='user',
        ),
    ]
