# Generated by Django 5.0.4 on 2025-04-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyBridge', '0003_alter_books_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='coverURL',
            field=models.URLField(blank=True, null=True),
        ),
    ]
