# Generated by Django 5.0.4 on 2025-04-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyBridge', '0004_books_coverurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookshelfs',
            name='ratings',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
