# Generated by Django 5.0.4 on 2025-04-03 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storyBridge', '0005_bookshelfs_ratings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookshelfs',
            old_name='ratings',
            new_name='rating',
        ),
    ]
