# Generated by Django 5.0.4 on 2025-04-15 15:05

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyBridge', '0008_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dateModified',
            field=models.DateTimeField(auto_now=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
