# Generated by Django 5.0.4 on 2025-04-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyBridge', '0010_remove_reviews_rating_remove_reviews_reviewtext_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='bookKey',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
