# Generated by Django 5.0.4 on 2025-04-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyBridge', '0011_books_bookkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profileImg',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
