# Generated by Django 5.0.4 on 2025-04-18 11:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyBridge', '0012_profile_profileimg'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='reviewLike', to=settings.AUTH_USER_MODEL),
        ),
    ]
