# Generated by Django 5.0.4 on 2025-04-19 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storyBridge', '0014_readingchallenge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_reads_book',
            name='book',
        ),
        migrations.RemoveField(
            model_name='user_reads_book',
            name='user',
        ),
        migrations.DeleteModel(
            name='Badge_Obtained_By_User',
        ),
        migrations.DeleteModel(
            name='User_Reads_Book',
        ),
    ]
