# Generated by Django 5.0.4 on 2025-04-22 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storyBridge', '0023_reviews_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='rating',
        ),
    ]
