# Generated by Django 5.0.4 on 2025-04-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyBridge', '0024_remove_reviews_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='bookKey',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
