# Generated by Django 5.0.4 on 2025-05-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyBridge', '0026_remove_reviews_bookkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookshelfs',
            name='bookshelfType',
            field=models.CharField(choices=[('Currently Reading', 'CurrentlyReading'), ('WTR', 'WantToRead'), ('RD', 'Read')], max_length=20),
        ),
    ]
