# Generated by Django 5.0.4 on 2025-05-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyBridge', '0027_alter_bookshelfs_bookshelftype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookshelfs',
            name='bookshelfType',
            field=models.CharField(choices=[('CR', 'CurrentlyReading'), ('WTR', 'WantToRead'), ('RD', 'Read'), ('DNF', 'DidNotFinish')], max_length=20),
        ),
    ]
