# Generated by Django 5.0.4 on 2025-05-04 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storyBridge', '0028_alter_bookshelfs_bookshelftype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badges',
            name='user',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.RemoveField(
            model_name='followers',
            name='author',
        ),
        migrations.RemoveField(
            model_name='followers',
            name='user',
        ),
        migrations.DeleteModel(
            name='Badges',
        ),
        migrations.DeleteModel(
            name='Followers',
        ),
    ]
