# Generated by Django 5.0.4 on 2025-05-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyBridge', '0029_remove_badges_user_delete_customuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
